<a href="https://colab.research.google.com/github/grmounica/Deep-Learning-Lab-Practice-work/blob/main/Neural_Networks_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1><center>Implementing NN using Numpy (Python) </center></h1>

importing the library

In [1]:
import numpy as np

creating the input array

In [2]:
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
print ('\n Input:')
print(X)


 Input:
[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]


creating the output array

In [3]:
y=np.array([[1],[1],[0]])
print ('\n Actual Output:')
print(y)


 Actual Output:
[[1]
 [1]
 [0]]


Sigmoid function

In [4]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))

Derivative of sigmoid function

In [5]:
def derivatives_sigmoid(x):
    return x * (1 - x)

initializing the variables

In [6]:
epoch=5000 
lr=0.1 
inputlayer_neurons = X.shape[1] 
hiddenlayer_neurons = 3 
output_neurons = 1 

initializing weights and bais

In [7]:
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [8]:
for i in range(epoch):
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr

In [9]:
print ('\n Output from the model:')
print (output)


 Output from the model:
[[0.96747623]
 [0.96033955]
 [0.05721557]]
